# Generated by Django 4.0.4 on 2022-05-14 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0002_alter_foods_calories_alter_foods_protein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_fridge',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.foods', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user_fridge',
            unique_together={('uid', 'fid')},
        ),
    ]
