# Generated by Django 4.0.4 on 2022-05-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_user_fridge_fid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_fridge',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.foods'),
        ),
    ]
